//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtlasSampleManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=.;Database=Atlas_PRODGCV_WOD;Trusted_Connection=True;")]
        public string AtlasGradeControlDatabase {
            get {
                return ((string)(this["AtlasGradeControlDatabase"]));
            }
            set {
                this["AtlasGradeControlDatabase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string AtlasOperation {
            get {
                return ((string)(this["AtlasOperation"]));
            }
            set {
                this["AtlasOperation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Intertek")]
        public string Laboratory {
            get {
                return ((string)(this["Laboratory"]));
            }
            set {
                this["Laboratory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Atlas")]
        public string AtlasCompany {
            get {
                return ((string)(this["AtlasCompany"]));
            }
            set {
                this["AtlasCompany"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ATLAS IRON PDO_BS_")]
        public string AtlasSubmissionBSNameSuffix {
            get {
                return ((string)(this["AtlasSubmissionBSNameSuffix"]));
            }
            set {
                this["AtlasSubmissionBSNameSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ATLAS IRON PDO_PS_")]
        public string AtlasSubmissionPSNameSuffix {
            get {
                return ((string)(this["AtlasSubmissionPSNameSuffix"]));
            }
            set {
                this["AtlasSubmissionPSNameSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Home\\Clients\\ati005\\data\\Samples\\Blastholes\\Submissions")]
        public string BSSubmissionDirectory {
            get {
                return ((string)(this["BSSubmissionDirectory"]));
            }
            set {
                this["BSSubmissionDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Home\\Clients\\ati005\\data\\Samples\\Blastholes\\GeochemicalResults")]
        public string BSResultsDirectory {
            get {
                return ((string)(this["BSResultsDirectory"]));
            }
            set {
                this["BSResultsDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Home\\Clients\\ati005\\data\\Samples\\Blastholes\\AcceptedResults")]
        public string BSAcceptedResultsDirectory {
            get {
                return ((string)(this["BSAcceptedResultsDirectory"]));
            }
            set {
                this["BSAcceptedResultsDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Home\\Clients\\ati005\\data\\Samples\\Product\\Submissions")]
        public string PSSubmissionDirectory {
            get {
                return ((string)(this["PSSubmissionDirectory"]));
            }
            set {
                this["PSSubmissionDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Home\\Clients\\ati005\\data\\Samples\\Product\\GeochemicalResults")]
        public string PSResultsDirectory {
            get {
                return ((string)(this["PSResultsDirectory"]));
            }
            set {
                this["PSResultsDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Home\\Clients\\ati005\\data\\Samples\\Product\\AcceptedResults")]
        public string PSAcceptedResultsDirectory {
            get {
                return ((string)(this["PSAcceptedResultsDirectory"]));
            }
            set {
                this["PSAcceptedResultsDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Home\\Clients\\ati005\\data\\Samples\\Blastholes\\ShotSampling")]
        public string LaboratoryEmailList {
            get {
                return ((string)(this["LaboratoryEmailList"]));
            }
            set {
                this["LaboratoryEmailList"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=AtlasProdGCV;Integrated Security=True")]
        public string AtlasProdGCVConnectionString {
            get {
                return ((string)(this["AtlasProdGCVConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CH")]
        public string PSChangeStockpileSampleType {
            get {
                return ((string)(this["PSChangeStockpileSampleType"]));
            }
            set {
                this["PSChangeStockpileSampleType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Home\\Clients\\ati005\\data\\Samples\\Blastholes\\ShotSampling")]
        public string BSPendingShotSampling {
            get {
                return ((string)(this["BSPendingShotSampling"]));
            }
            set {
                this["BSPendingShotSampling"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\per-pdms\\iHub\\Pending")]
        public string iHubPendingDirectory {
            get {
                return ((string)(this["iHubPendingDirectory"]));
            }
            set {
                this["iHubPendingDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\per-pdms\\iHub\\Processed")]
        public string iHubProcessedDirectory {
            get {
                return ((string)(this["iHubProcessedDirectory"]));
            }
            set {
                this["iHubProcessedDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\per-pdms\\iHub\\Processing")]
        public string iHubProcessingDirectory {
            get {
                return ((string)(this["iHubProcessingDirectory"]));
            }
            set {
                this["iHubProcessingDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\per-pdms\\iHub\\Error")]
        public string iHubErrorDirectory {
            get {
                return ((string)(this["iHubErrorDirectory"]));
            }
            set {
                this["iHubErrorDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\temp\\")]
        public string TempDirectory {
            get {
                return ((string)(this["TempDirectory"]));
            }
            set {
                this["TempDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=per10dc01\\\\atlasiron;Database=Atlas_PRODGCV_WOD;Trusted_Connection=False;u" +
            "ser=gcv;password=praxis666!")]
        public string AtlasMinemarketLinkDatabase {
            get {
                return ((string)(this["AtlasMinemarketLinkDatabase"]));
            }
            set {
                this["AtlasMinemarketLinkDatabase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CS")]
        public string PSSttartOfShiftStockpileSampleType {
            get {
                return ((string)(this["PSSttartOfShiftStockpileSampleType"]));
            }
            set {
                this["PSSttartOfShiftStockpileSampleType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CE")]
        public string PSEndOfShiftStockpileSampleType {
            get {
                return ((string)(this["PSEndOfShiftStockpileSampleType"]));
            }
            set {
                this["PSEndOfShiftStockpileSampleType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PSShiftTimeOffset {
            get {
                return ((double)(this["PSShiftTimeOffset"]));
            }
            set {
                this["PSShiftTimeOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W:\\12_Daily_Report\\Sample Manager")]
        public string ConfigDirectory {
            get {
                return ((string)(this["ConfigDirectory"]));
            }
            set {
                this["ConfigDirectory"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WOD-FS01;Initial Catalog=Atlas_PRODGCV_WOD;Integrated Security=True")]
        public string Atlas_PRODGCV_WODConnectionString {
            get {
                return ((string)(this["Atlas_PRODGCV_WODConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Main</string>\r\n  <string>Auxillary</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CrusherStreams {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CrusherStreams"]));
            }
            set {
                this["CrusherStreams"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=Atlas_PRODGCV_WOD;Integrated Security=True")]
        public string Atlas_PRODGCV_WODConnectionString1 {
            get {
                return ((string)(this["Atlas_PRODGCV_WODConnectionString1"]));
            }
        }
    }
}
